import Head from "next/head";
import { useState, useEffect } from "react";

import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const [currentNum, setCurrentNum] = useState<number>(1000);
  const [rouletteNum, setRouletteNum] = useState<number | null>(null);
  const [status, setStatus] = useState<null | string>(null);

  const rollDown = async () => {
    const amtOfRolls = Math.floor(Math.random() * 21);
    const result = await _rollDown(amtOfRolls, currentNum);
    result && setCurrentNum(result);
    setRouletteNum(null);
  };

  const _rollDown = async (amtOfRolls: number, rolledNum: number) => {
    let curRoll = 1;
    while (curRoll < amtOfRolls) {
      amtOfRolls;
      await rouletteSpin(curRoll, rolledNum);
      curRoll++;
    }
    return rouletteNum;
  };

  const rouletteSpin = (curRoll: number, rolledNum: number): Promise<void> => {
    return new Promise((resolve) =>
      setTimeout(() => {
        setRouletteNum(Math.floor(Math.random() * rolledNum) + 1);
        resolve();
      }, curRoll * 100),
    );
  };

  const reset = () => {
    setCurrentNum(1000);
    setStatus(null);
  };
  useEffect(() => {
    if (currentNum === 1) setStatus("Defeated");
    console.log(currentNum);
  }, [currentNum]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-cyan-900">
        <div className="text-lg text-slate-500">Deathroll</div>
        <div>{rouletteNum ?? currentNum}</div>
        {status && <div className="m-3 text-red-500">{status}</div>}
        <button onClick={rollDown} disabled={currentNum === 1}>
          Roll
        </button>
        {currentNum === 1 && <button onClick={reset}>Play Again</button>}
      </main>
    </>
  );
}
