import Head from "next/head";
import Link from "next/link";
import { MouseEventHandler, useState, MouseEvent, useEffect } from "react";

import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const [currentRoll, setCurrentRoll] = useState<number>(1000);
  const [status, setStatus] = useState<null | string>(null);
  const rollDown = () => {
    setTimeout(() => {
      setCurrentRoll((roll) => Math.floor(Math.random() * roll) + 1);
    }, 500);
  };

  const reset = () => {
    setCurrentRoll(1000);
    setStatus(null);
  };
  useEffect(() => {
    if (currentRoll === 1) setStatus("Defeated");
  }, [currentRoll]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-lg text-slate-500">Deathroll</div>
        <div>{currentRoll}</div>
        {status && <div className="m-3 text-red-500">{status}</div>}
        <button onClick={rollDown}>Roll</button>
        <button onClick={reset}>Reset</button>
      </main>
    </>
  );
}
